
get_request = ->
  last_id = $('.message').last().attr('data-id')
  $.ajax
    type: 'GET'
    url: $(this).attr('href')
    data: last_id: last_id
    dataType: 'script'
  setTimeout get_request, 1000
  return

$(document).ready ->
  get_request()
  return


# ---
# generated by js2coffee 2.1.0
